Parametrize number of similar questions generated
GoogleCloudPlatform/platform-gen-ai pull request #15
Opened 2024-04-30 19:52 UTC by daureng

# Summary
Parametrized the number of similar questions generated by llm. If it is set to 0, similar questions are not generated.

# Tests
Tested manually using different numbers as parameters

2024-04-30 20:37 UTC, misha-chertushkin commented on gen_ai/llm.yaml
> +    - Limit the number of similar questions to {similar_questions_number}.
I guess you need to pass the similar_questions_number as the parameter to the LLMChain, so you need to modify provide_chain in ioc_container.py

2024-04-30 20:38 UTC, misha-chertushkin commented on gen_ai/common/retriever.py
> +    if similar_questions_number:
if similar questions is 0 lets just populate questions = [question] and completely skip any other logic

2024-04-30 20:38 UTC, misha-chertushkin requested changes
Looks good, posted 2 small suggestions

2024-04-30 20:55 UTC, daureng commented on gen_ai/common/retriever.py
> +    if similar_questions_number:
good one, fixed

2024-04-30 21:09 UTC, daureng commented on gen_ai/llm.yaml
> +    - Limit the number of similar questions to {similar_questions_number}.
Fixed, how did it even work

2024-05-01 14:19 UTC, misha-chertushkin approved these changes
Great job! LGTM

2024-05-01 18:09 UTC, anna-novakovska approved these changes
lgtm

2024-05-01 20:54 UTC, merged